broadcasts:
  # /t ask (Permission: townyrequest.t.ask)
  t-ask:
    # Объявление при наборе:
    message: "&8[&a⭐&8] &7Игрок &a{PLAYER} &7желает присоединиться к городу!"

    # Успешная отправка:
    message-successfully: "&aВы успешно попросились в город!"

    # Текст кнопки:
    button-message: "&f[Пригласить в город]"

    # Подсказка при наведении на кнопку:
    button-prompt: "&fНажмите, чтобы принять &a{PLAYER} &fв свой город!"

    # Звук при отправке объявления:
    # Кстати, на PolitMine звука нет, это моя идея :)
    sound-t-ask: "ENTITY_EXPERIENCE_ORB_PICKUP"

    # Сообщение об отказе отправить объявление, из-за отсутствия permission'а:
    no-permission: "&cУ вас нет прав на отправку запроса в город!"

    # Сообщение об отказе отправить объявление, из-за отсутствия того, что игрок уже состоит в городе:
    refusal: "&cВы уже состоите в городе!"
  # /t selection (Permission: townyrequest.t.selection)
  t-selection:
    # Объявление при наборе:
    message: "&8[&a⭐&8] &aМировая пресса! &7Город &a{TOWN} &7объявил набор горожан к себе! Вы можете вступить, нажав кнопку:"

    # Успешная отправка:
    message-successfully: "&aВы успешно объявили набор в город!"

    # Текст кнопки:
    button-message: "&f[Вступить в город]"

    # Подсказка при наведении на кнопку:
    button-prompt: "&fНажмите, чтобы вступить в город &a{TOWN}&f!"

    # Звук при отправке объявления:
    sound-t-selection: "ENTITY_EXPERIENCE_ORB_PICKUP"

    # Сообщение об отказе отправить объявление, из-за отсутствия permission'а:
    no-permission: "&cУ вас нет прав для объявления набора в город!"

    # Сообщение об отказе отправить объявление, из-за отсутствия города у игрока:
    no-town: "&cУ вас нет города!"
  # /n ask (Permission: townyrequest.t.ask)
  n-ask:
    # Объявление при наборе:
    message: "&8[&a⭐&8] &aМировая пресса! &7Город &a{TOWN} &7желает присоединиться к нации!"

    # Успешная отправка:
    message-successfully: "&aВаш город успешно попросился в нацию!"

    # Текст кнопки:
    button-message: "&f[Пригласить в нацию]"

    # Подсказка при наведении на кнопку:
    button-prompt: "&fНажмите, чтобы принять &a{TOWN} &fв свою нацию!"

    # Звук при отправке объявления:
    sound-n-ask: "ENTITY_EXPERIENCE_ORB_PICKUP"

    # Сообщение об отказе отправить объявление, из-за отсутствия permission'а:
    no-permission: "&cУ вас нет прав на отправку запроса в нацию!"

    # Сообщение об отказе отправить объявление, из-за отсутствия того, что игрок уже состоит в городе:
    refusal: "&cВаш город уже состоит в нации!"

  # /n selection (Permission: townyrequest.n.selection)
  n-selection:
    # Объявление при наборе:
    message: "&8[&a⭐&8] &aМировая пресса! &7Нация &a{NATION} &7объявила миру, что ищет новые города для присоединения к себе! Вы можете вступить, нажав кнопку:"

    # Успешная отправка:
    message-successfully: "&aВы успешно объявили набор в нацию!"

    # Текст кнопки:
    button-message: "&f[Вступить в нацию]"

    # Подсказка при наведении на кнопку:
    button-prompt: "&fНажмите, чтобы вступить в нацию &a{NATION}&f!"

    # Звук при отправке объявления:
    sound-n-selection: "ENTITY_EXPERIENCE_ORB_PICKUP"

    # Сообщение об отказе отправить объявление, из-за отсутствия permission'а:
    no-permission: "&cУ вас нет прав для объявления набора в нацию!"

    # Сообщение об отказе отправить объявление, из-за отсутствия города у игрока:
    no-town: "&cУ вас нет города!"

    # Сообщение об отказе отправить объявление, из-за отсутствия нации у игрока:
    no-nation: "&cУ вас нет нации!"